import { useState, useEffect } from 'react';
import { coaching_getBatches, coaching_addBatch, coaching_getStudents, coaching_assignStudents } from '../../api/client';
import { fmt } from '../../utils/format';
export default function Batches() {
  const [batches,setBatches]=useState([]); const [students,setStudents]=useState([]); const [loading,setLoading]=useState(true);
  const [showForm,setShowForm]=useState(false); const [form,setForm]=useState({name:'',subject:'',schedule:'',maxStudents:30,fee_monthly:0});
  const [saving,setSaving]=useState(false); const [msg,setMsg]=useState(null); const [assignBatch,setAssignBatch]=useState(null); const [sel,setSel]=useState([]);
  useEffect(()=>{Promise.all([coaching_getBatches(),coaching_getStudents()]).then(([b,s])=>{setBatches(b.batches||[]);setStudents(s.students||[]);setLoading(false);}).catch(()=>setLoading(false));},[]);
  const setF=(k,v)=>setForm(f=>({...f,[k]:v}));
  async function save(){if(!form.name){setMsg({type:'error',text:'Enter name'});return;}setSaving(true);try{const r=await coaching_addBatch(form);setBatches(p=>[{...form,id:r.id,status:'Active',studentCount:0,faculty:[]},...p]);setShowForm(false);setMsg(null);}catch(e){setMsg({type:'error',text:e.message});}setSaving(false);}
  async function assign(){if(!assignBatch||!sel.length)return;setSaving(true);try{await coaching_assignStudents({batch_id:assignBatch.id,students:JSON.stringify(sel)});const b=await coaching_getBatches();setBatches(b.batches||[]);setAssignBatch(null);setSel([]);}catch(e){setMsg({type:'error',text:e.message});}setSaving(false);}
  if(loading)return<div className="loader"><div className="loader-ring"/></div>;
  return(<div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'20px'}}><div><h2 style={{fontSize:'20px',fontWeight:700,margin:0}}>Batches</h2><p style={{fontSize:'13px',color:'var(--muted)',margin:0}}>{batches.length} batch(es)</p></div><button className="form-btn primary" onClick={()=>setShowForm(s=>!s)}>+ New Batch</button></div>
    {showForm&&<div className="form-card"><div className="form-section-title">New Batch</div><div className="form-grid"><div className="fg"><label className="fl">Name *</label><input className="fi" value={form.name} onChange={e=>setF('name',e.target.value)} placeholder="e.g. JEE Batch A"/></div><div className="fg"><label className="fl">Subject</label><input className="fi" value={form.subject} onChange={e=>setF('subject',e.target.value)}/></div><div className="fg"><label className="fl">Schedule</label><input className="fi" value={form.schedule} onChange={e=>setF('schedule',e.target.value)} placeholder="Mon,Wed,Fri 6-8PM"/></div><div className="fg"><label className="fl">Max Students</label><input className="fi" type="number" value={form.maxStudents} onChange={e=>setF('maxStudents',e.target.value)}/></div><div className="fg"><label className="fl">Monthly Fee ₹</label><input className="fi" type="number" value={form.fee_monthly} onChange={e=>setF('fee_monthly',e.target.value)}/></div></div>{msg&&<div style={{marginTop:'10px',padding:'8px',borderRadius:'8px',fontSize:'12px',background:'rgba(239,68,68,.1)',color:'#fca5a5'}}>{msg.text}</div>}<div style={{display:'flex',gap:'8px',marginTop:'14px'}}><button className="form-btn primary" onClick={save} disabled={saving}>{saving?'...':'Create'}</button><button className="form-btn secondary" onClick={()=>setShowForm(false)}>Cancel</button></div></div>}
    {assignBatch&&<div className="form-card" style={{borderLeft:'3px solid #10b981'}}><div style={{fontWeight:600,marginBottom:'12px'}}>Assign to: <span style={{color:'#10b981'}}>{assignBatch.name}</span></div><div style={{maxHeight:'200px',overflowY:'auto',marginBottom:'12px'}}>{students.map(s=><label key={s.id} style={{display:'flex',alignItems:'center',gap:'8px',padding:'6px 0',cursor:'pointer',fontSize:'13px'}}><input type="checkbox" checked={sel.includes(s.id)} onChange={e=>setSel(p=>e.target.checked?[...p,s.id]:p.filter(x=>x!==s.id))} style={{width:'16px',height:'16px'}}/>{s.name}</label>)}</div><div style={{display:'flex',gap:'8px'}}><button className="form-btn primary" onClick={assign} disabled={saving||!sel.length}>{saving?'...':'Assign'}</button><button className="form-btn secondary" onClick={()=>{setAssignBatch(null);setSel([]);}}>Cancel</button></div></div>}
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:'14px'}}>{batches.map(b=><div key={b.id} style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'14px',padding:'18px',borderTop:'3px solid #8b5cf6'}}>
      <div style={{display:'flex',justifyContent:'space-between',marginBottom:'12px'}}><div><div style={{fontSize:'16px',fontWeight:700}}>{b.name}</div><div style={{fontSize:'12px',color:'var(--muted)',marginTop:'2px'}}>{b.subject||'—'} · {b.schedule||'—'}</div></div>
      <div style={{textAlign:'center'}}><div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'16px',fontWeight:800,color:'#8b5cf6'}}>{b.studentCount}/{b.maxStudents}</div><div style={{width:'60px',height:'4px',borderRadius:'2px',background:'rgba(139,92,246,.15)',marginTop:'4px'}}><div style={{height:'100%',borderRadius:'2px',background:'#8b5cf6',width:`${Math.min(100,(b.studentCount/b.maxStudents)*100)}%`}}/></div></div></div>
      <div style={{fontSize:'12px',color:'var(--muted)',marginBottom:'12px'}}>₹{fmt(b.fee_monthly)}/mo</div>
      <button onClick={()=>{setAssignBatch(b);setSel([]);}} style={{padding:'6px 14px',borderRadius:'8px',border:'1px solid rgba(16,185,129,.3)',background:'rgba(16,185,129,.06)',color:'#6ee7b7',fontSize:'11px',fontWeight:600,cursor:'pointer',fontFamily:'inherit'}}>+ Students</button>
    </div>)}</div>
  </div>);
}
